### ISSUE TITLE
[RFE] setup ci using github actions

### ISSUE THREAD

**Issue by blaisep** [darrylwest/pydomkeys#2]
Background: Github will run tasks against the repo.

Scenario: a commit is pushed from a remote
Given: A push stage is triggered
When the stage is complete
Then a new console log appears in the Actions tab

Given a badge is configured in the stage
When the job is complete
Then the status of the badge is updated.

**Comment by blaisep** [comment]
@darrylwest , I'm just dropping down some ideas for now, feel free to close with wontfix if you like.

**Comment by darrylwest** [comment]
done
