### ISSUE TITLE
[RFE] Version-specific docs

### ISSUE THREAD

**Issue by blaisep** [darrylwest/pydomkeys#3]
Background: Docs are specific to the version of the binaries.

Scenario: A reader refers to a doc
Given A branch has a corresponding doc
When the branch is updated
Then the doc revision matches the git sha

**Comment by darrylwest** [comment]
Would that be in lieu of a single change log, or to supplement?  and links from the change log to the sha?

**Comment by blaisep** [comment]
you'll see 😀

**Comment by blaisep** [comment]
https://github.com/darrylwest/pydomkeys/pull/5

After we clean this up a bit, we can add a version for `develop` so that folks can see the stable docs and also new work in progress.

**Comment by darrylwest** [comment]
done
